###
GET http://localhost:8080/assunto/v1

###
GET http://localhost:8080/interessado/v1

###
GET http://localhost:8080/processo/v1

###
GET http://localhost:8080/assunto/v1/2

###
GET http://localhost:8080/interessado/v1/2

###
GET http://localhost:8080/interessado/v1?nu_identificacao=22222222222

###
GET http://localhost:8080/processo/v1/1

###
GET http://localhost:8080/processo/v1?id-interessado=1

###
GET http://localhost:8080/processo/v1?nu-processo=2

###
POST http://localhost:8080/assunto/v1
Content-Type: application/json

{
  "descricao": "descricao",
  "dtCadastro": "2021-05-24",
  "flAtivo": "n"
}

###
POST http://localhost:8080/interessado/v1
Content-Type: application/json

{
  "nmInteressado": "fulano",
  "nuIdentificacao": "22222222222",
  "dtNascimento": "1951-01-01",
  "flAtivo": "n"
}

###
POST http://localhost:8080/processo/v1
Content-Type: application/json

{
  "sgOrgaoSetor": "SOFT",
  "nuAno": "2021",
  "descricao": "descricao",
  "cdAssunto": {
    "id": 1
  },
  "cdInteressado": {
    "id": 1
  }
}

###
DELETE http://localhost:8080/processo/v1/3

###
PUT http://localhost:8080/processo/v1/1
Content-Type: application/json

{
  "descricao": "asdasd"
}

###
GET http://localhost:8080/processo/v1/1

###
